controllers/UserController.php
<?php
/**
 * Last modified: 18.10.30 03:03:41
 * Hash: e33f1f73709bef6fdd12e6f159d454d838271d76
 */

namespace app\controllers;

use app\controllers\base\RestController;
use app\helpers\Utils;
use app\models\Email;
use app\models\form\Login;
use app\models\form\Password;
use app\models\form\RequestPasswordReset;
use app\models\Log;
use app\models\Token;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\ForbiddenHttpException;
use yii\web\MethodNotAllowedHttpException;


class UserController extends RestController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'request', 'reset', 'profile'],
                'rules' => [
                    'guest' => [
                        'allow' => true,
                        'actions' => ['request', 'reset'],
                        'roles' => ['?']
                    ],
                    'member' => [
                        'allow' => true,
                        'actions' => ['profile', 'logout'],
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }

    protected function saveSponsor($nick)
    {
        $nick = $nick ?: Yii::$app->request->getCookie('sponsor', Yii::$app->params['root']);
        if (Yii::$app->params['root'] !== $nick) {
            $expire = time() + 3600 * 24 * 30 * 12 * 10;
//            Yii::$app->request->cookies->add(new Cookie([
//                'name' => 'sponsor',
//                'value' => $nick,
//                'expire' => $expire
//            ]));
            setcookie('sponsor', $nick, $expire, '/');
        }
        return $nick;
    }

    public function actionSignup($nick = null)
    {
        if (!Yii::$app->user->getIsGuest()) {
            return $this->redirect(['user/profile', 'nick' => Yii::$app->user->identity->nick]);
        }

        $this->layout = 'outdoor';
        $nick = $this->saveSponsor($nick);
        $model = new User(['scenario' => User::SCENARIO_REGISTER]);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->parent = User::getIdByNick($model->sponsor ?: $nick ?: Yii::$app->params['root']);
            $model->generateSecret();
            $model->save(false);
            if (Yii::$app->user->login($model)) {
                Email::send($model->email,
                    Yii::t('app', '{name}: Welcome', ['name' => Yii::$app->name]),
                    Yii::t('app', "Dear, {nick}\nThank you for registration at {name}", [
                        'nick' => $model->nick,
                        'name' => Yii::$app->name
                    ]));
                Log::log('user', 'signup', ['ip' => $model->ip]);
                if (Yii::$app->has('telegram') && Yii::$app->telegram->getStorage()->get('signup')) {
                    Yii::$app->telegram->sendText("Welcome $model->nick ($model->email)! Invited by "
                        . $model->parentObject->nick);
                }
                return $this->redirect(['user/profile', 'nick' => $model->nick]);
            }
        } else {
            $model->sponsor = $nick;
//            if ('GET' !== Yii::$app->request->getMethod()) {
//                Yii::$app->request->save();
//            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionLogin($nick = null)
    {
        if (!Yii::$app->user->getIsGuest()) {
            return $this->redirect(['user/profile', 'nick' => Yii::$app->user->identity->nick]);
        }

        $this->layout = 'outdoor';
        $this->saveSponsor($nick);
        $data = empty(Yii::$app->params['demo']) ? [] : Yii::$app->params['demo'];
        $model = new Login($data);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $data = ['ip' => $model->ip];
            $user = null;
            if (Login::checkLoginAttempt(['ip' => Yii::$app->request->getUserIP()])) {
                $user = $model->getUser();
                if ($user) {
                    if (Login::checkLoginAttempt(['user' => $user->id])) {
                        if ($user->secret) {
                            if ($user->validatePassword($model->password)) {
                                if (Yii::$app->params['admin'] && !Utils::isAdmin($user->nick)) {
                                    $model->addError('login', Yii::t('app', 'User is not admin'));
                                } else {
                                    Yii::$app->user->login($user);
                                    Log::log('auth', 'login', $data);
                                    if (isset($user->refback) && $user->refback > 0) {
                                        Yii::$app->session->addFlash('warning',
                                            Yii::t('app', 'Your refback is {percent}%', [
                                                'percent' => (int)round($user->refback * 100)
                                            ]));
                                    }
                                    return $this->redirect(['user/profile', 'nick' => $user->nick]);
                                }
                            } else {
                                $model->addError('password', Yii::t('app', 'Invalid password'));
                            }
                        } else {
                            Yii::$app->session->addFlash('error', Yii::t('app', 'You are banned'));
                        }
                    }
                } else {
                    $model->addError('login', Yii::t('app', 'User does not exists'));
                }
            }
            if (!$user) {
                $data['login'] = $model->login;
            }
            Log::log('auth', 'invalid', $data, $user ? $user->id : null);
        }
//        elseif ('GET' !== Yii::$app->request->getMethod()) {
//            Yii::$app->request->save();
//        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout($ip = null)
    {
        if (YII_DEBUG || 'POST' === Yii::$app->request->getMethod()) {
            $id = Yii::$app->user->identity->id;
            Yii::$app->user->logout(false);
            Log::log('auth', 'logout', $ip ? ['ip' => $ip] : null, $id);
            return $this->redirect(['user/login']);
        }
        throw new MethodNotAllowedHttpException();
    }

    public function actionProfile(string $nick)
    {
        if (!Utils::isOwn($nick)) {
//            throw new ForbiddenHttpException('You cannot access not your profile: ' . $nick);
            return $this->redirect(['user/profile', 'nick' => Yii::$app->user->identity]);
        }
        $this->view->params['breadcrumbs'][] = [
            'label' => Yii::t('app', 'Dashboard'),
            'url' => ['user/profile', 'nick' => $nick]
        ];
        $vars = Yii::$app->user->identity->getInformers(Yii::$app->request->getCurrency());
        $vars['investments'] = Yii::$app->user->identity->getNodes();
        $vars['reflink'] = Yii::$app->user->identity->getReflink();
        return $this->render('profile', $vars);
    }

    public function actionRequest()
    {
        $this->layout = 'outdoor';
        $model = new RequestPasswordReset();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $model->getUser();
            if ($user) {
                if ($user->secret) {
                    $code = $user->generateCode();
                    if (!$code) {
                        throw new ForbiddenHttpException();
                    }
                    $subject = Yii::t('app', '{name}: Password Recovery', ['name' => Yii::$app->name]);
                    $url = Url::to(['user/reset', 'code' => $code], true);
                    $text = Yii::t('app', 'Recover your password {url}', ['url' => $url]);
                    Email::send($user->email, $subject, $text);
                    Log::log('password', 'request', ['ip' => $model->ip]);
                    Yii::$app->session->addFlash('success', Yii::t('app', 'Check your email'));
                } else {
                    Yii::$app->session->addFlash('error', Yii::t('app', 'You are banned'));
                }
            } else {
                Yii::$app->session->addFlash('error', Yii::t('app', 'User does not exists'));
            }
        }
        return $this->render('request', ['model' => $model]);
    }

    public function actionReset(string $code)
    {
        $this->layout = 'outdoor';
        $model = new Password(['scenario' => Password::SCENARIO_RESET]);
        $token = Token::findOne(['id' => $code]);
        if ($token) {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $user = User::findOne(['id' => $token->user]);
                $user->password = $model->new;
                $user->generateSecret();
                Log::log('password', 'reset', ['ip' => $model->ip], $user->id);
                if ($user->save(false) && $token->delete()) {
                    Yii::$app->session->addFlash('success', Yii::t('app', 'Password changed'));
                }
                return $this->redirect(['user/login']);
            }
        } else {
            throw new ForbiddenHttpException('Password recovery code not found or already used');
        }
        return $this->render('reset', ['model' => $model]);
    }

    public function actionAuthorize($nick, $token)
    {
        Yii::$app->request->save();
        $auth = Token::findOne(['id' => $token]);
        if ($auth) {
            $user = User::findOne(['nick' => $nick]);
            if ($user) {
                if ($auth->userObject->admin) {

views/user/login.php
<?php
/**
 * Last modified: 18.07.22 10:35:21
 * Hash: 5b0cc5085a59b2c2eedc902986cb45ac5e53399a
 * @var \app\models\form\Login $model
 * @var $this \yii\web\View
 */

use app\models\User;
use app\widgets\Alert;
use himiklab\yii2\recaptcha\ReCaptcha;
use yii\bootstrap\Html;
use yii\widgets\ActiveForm;

?>
<div class="user login">
    <div class="logo">
        <img src="/images/logo-black.png" alt="AI Logistics">
    </div>
    <h1><?= Yii::t('app', 'Login') ?></h1>
    <p class="description"><?= Yii::t('app', 'Enter your login and password to use your personal account') ?></p>

    <?= Alert::widget() ?>

    <?php $form = ActiveForm::begin(); ?>
    <div class="fields">
        <?= $form->field($model, 'login')
            ->textInput([
                'maxlength' => User::NICK_LENGTH,
                'placeholder' => Yii::t('app', 'Enter Your Login'
                )])
            ->label(false) ?>
        <?= $form->field($model, 'password')
            ->passwordInput([
                'maxlength' => User::PASSWORD_LENGTH,
                'placeholder' => Yii::t('app', 'Enter Your Password')
            ])
            ->label(false) ?>
        <?= $form->field($model, 'ip')->hiddenInput()->label(false) ?>
    </div>
    <div class="captcha">
        <?php
        //        if (Yii::$app->settings->get('auth-captcha', 0) > 0) {
        //            echo $form->field($model, 'captcha')->widget(Captcha::class)->label(false);
        //        }
        if (Yii::$app->settings->get('auth-recaptcha', 0) > 0) {
            echo $form->field($model, 'captcha')->widget(ReCaptcha::class, [
                'size' => ReCaptcha::SIZE_NORMAL
            ])->label(false);
        }
        ?>
    </div>
    <div class="control">
        <?= Html::submitButton(Yii::t('app', 'Login')) ?>
        <?= Html::a(Yii::t('app', 'Signup'), ['user/signup']) ?>
        <?= Html::a(Yii::t('app', 'Forgot password?'), ['user/request']) ?>
    </div>

    <?php ActiveForm::end() ?>
</div>

views/user/profile.php
<?php
/**
 * Last modified: 18.08.11 12:14:26
 * Hash: 331bf117ebedb67550f40c842f3a56f5d406c886
 * @var $this \yii\web\View
 */

use app\helpers\Html;

?>

<div class="user profile">
    <?php if (Yii::$app->user->identity->agreement): ?>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 verif">
            <p>Вывод активирован</p>
        </div>
    <?php else: ?>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 noverif">
            <p>
                Отправьте договор для активации вывода.
                <a href="//ai-logist.com/wp-content/uploads/2018/08/Dogovor.pdf" target="_black">Скачать договор</a>.
                Договор отправлять на Email: <a href="mailto:ai.logist.verif@gmail.com">ai.logist.verif@gmail.com</a>
            </p>
        </div>
    <?php endif ?>

    <div class="sortable col-lg-6 col-md-6 col-sm-12 col-xs-12" id="informer">
        <div class="row">
            <div class="invested col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <div class="informer" v-cloak>
                    <span class="name"><?= Yii::t('app', 'Invested') ?></span>
                    <div class="value money" v-bind:data-currency="currency">{{ buy | factor(currency) }}</div>
                </div>
            </div>
            <div class="income col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <div class="informer" v-cloak>
                    <span class="name"><?= Yii::t('app', 'Income') ?></span>
                    <div class="value money" v-bind:data-currency="currency">{{ accrue | factor(currency) }}</div>
                </div>
            </div>
            <div class="withdraw col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <div class="informer no-margin-bottom" v-cloak>
                    <span class="name"><?= Yii::t('app', 'Withdrawn') ?></span>
                    <div class="value money" v-bind:data-currency="currency">{{ withdraw | factor(currency) }}</div>
                </div>
            </div>
            <div class="referral col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <div class="informer no-margin-bottom" v-cloak>
                    <span class="name"><?= Yii::t('app', 'Affiliate profit') ?></span>
                    <div class="value money" v-bind:data-currency="currency">{{ bonus | factor(currency) }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class="turnover col-lg-3 col-md-3 col-sm-12 col-xs-12">
        <div class="informer no-margin-bottom">
            <span class="name"><?= Yii::t('app', 'Turnover') ?></span>
            <span class="description"><?= Yii::t('app', 'Career progress in {name}', ['name' => Yii::$app->name]) ?></span>
            <?= Html::tag('span', $turnover, ['class' => 'money usd']) ?>
            <div class="line-grey"></div>
            <span class="name"><?= Yii::t('app', 'Career') ?></span>
            <div class="padding-progress">
                <div class="progres">
                    <div class="progress-bg">
                        <div class="progress-bar" v-bind:style="{width: (100 * grade.id / grades.length) + '%' }"></div>
                        <div class="progress-check"></div>
                    </div>
                </div>
            </div>
            <div class="stats-rung" v-cloak>
                <div class="your-rung">
                    <p>{{ t(grade.name) }}</p>
                </div>
                <div v-if="nextGrade" class="next-rung">
                    <p>{{ t(nextGrade.name) }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="referral-link col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <h2><?= Yii::t('app', 'Your referral link') ?></h2>
        <?= Html::input('text', 'reflink', $reflink) ?>
        <div class="statistics">
            <div class="follow">
                <span class="value"><?= $follows ?></span>&nbsp;
                <span class="name"><?= Yii::t('app', 'follows') ?></span>
            </div>
            <div class="registration">
                <span class="value"><?= $children ?></span>&nbsp;
                <span class="name"><?= Yii::t('app', 'registrations') ?></span>
            </div>
            <div class="node">
                <span class="value"><?= $nodes ?></span>&nbsp;
                <span class="name"><?= Yii::t('app', 'investments') ?></span>
            </div>
        </div>
    </div>
    <div class="col-lg-3 invest-button col-md-3 col-sm-12 col-xs-12">
        <?= Html::a(Yii::t('app', 'Invest'), ['program/index'], ['id' => 'invest']) ?>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
        <div id="chart">
            <div class="chart-header">
                <h3><?= Yii::t('app', 'Income') ?></h3>
                <div class="control" v-cloak>
                    <div class="currency">
                        <p class="name"><?= Yii::t('app', 'Choose currency:') ?> </p>
                        <div class="widget dropdown">
                            <div class="value dropdown-toggle"
                                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ currency }}
                            </div>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a v-for="c in currencies"
                                   v-on:click="load(c)"
                                   v-bind:href="'#' + c"
                                   class="dropdown-item">
                                    {{ c }}
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="choose-mount">
                        <p class="name"><?= Yii::t('app', 'Choose month:') ?></p>
                        <div class="widget dropdown">
                            <div data-toggle="dropdown" class="value dropdown-toggle mounth">
                                {{ months[month] }}
                            </div>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a v-bind:href="'#' + m"
                                   v-bind:class="{'dropdown-item': true, current: m === month}"
                                   v-for="(label, m) in months"
                                   v-on:click="month = +m; loadChart()">{{ label }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <svg width="100%" height="210"></svg>

            <div class="line-box">
                <div class="line-grey"></div>
            </div>

            <div class="summary" v-cloak>
                <div class="income">
                    <div class="name"><?= Yii::t('app', 'Monthly income:') ?></div>
                    <div class="value money" v-bind:data-currency="currency">{{ monthIncome }}</div>
                </div>
                <div class="expense">
                    <div class="name"><?= Yii::t('app', 'Monthly expense:') ?></div>
                    <div class="value money" v-bind:data-currency="currency">{{ monthExpense }}</div>
                </div>
            </div>
        </div>
    </div>
    <div id="nodes">
        <?= $this->render('@app/views/node/index', ['models' => $investments]) ?>
    </div>
</div>

views/user/request.php
<?php

/**
 * Last modified: 18-05-09 00:46:29
 * Hash: 803bae603b5941d73afc48b0d80b762e2d0d1382
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\form\RequestPasswordReset
 * @var $form ActiveForm
 */

use app\widgets\Alert;
use yii\bootstrap\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Password recovery request');
?>

<div class="user request">
    <div class="logo">
        <img src="/images/logo-black.png" alt="AI Logistics">
    </div>

    <?= Alert::widget() ?>

    <?php $form = ActiveForm::begin(); ?>
    <h1><?= Yii::t('app', 'Reset password') ?></h1>

    <div class="fields">
        <?= $form->field($model, 'email')
            ->input('email', ['placeholder' => Yii::t('app', 'Enter Your Email')])
            ->label(false)
        ?>
        <?= $form->field($model, 'ip')->hiddenInput()->label(false) ?>
    </div>

    <div class="control">
        <?= Html::submitButton(Yii::t('app', 'Send Email'),
            ['class' => 'button full-width']) ?>

        <?= Html::a(Yii::t('app', 'Signup'), ['user/signup']) ?>
        <?= Html::a(Yii::t('app', 'Login'), ['user/login']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/user/reset.php
<?php

/**
 * Last modified: 18.05.22 03:13:36
 * Hash: 32fc74d1da56f2c6b37e22761fbef0e512644484
 * @var $this yii\web\View
 * @var $message string
 * @var $form ActiveForm
 * @var $model \app\models\form\Password
 */

use app\models\User;
use app\widgets\Alert;
use yii\bootstrap\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t( 'app', 'Password Recovery' );

?>

<div class="user login">
    <div class="logo">
        <img src="/images/logo-black.png" alt="AI Logistics">
    </div>
    <h1><?= Yii::t( 'app', 'Reset password' ) ?></h1>

    <div class="logo">
        <img src="/images/logo-black.png" alt="AI Logistics">
    </div>

	<?= Alert::widget() ?>

	<?php $form = ActiveForm::begin(); ?>

    <div class="fields">
		<?= $form->field( $model, 'new' )
            ->passwordInput(['maxlength' => User::PASSWORD_LENGTH]) ?>
		<?= $form->field( $model, 'repeat' )
            ->passwordInput(['maxlength' => User::PASSWORD_LENGTH]) ?>
		<?= $form->field( $model, 'ip' )->hiddenInput()->label( false ) ?>
    </div>

    <div class="control">
		<?= Html::submitButton( Yii::t( 'app', 'Reset' ),
			[ 'class' => 'button full-width' ] ) ?>
		<?= Html::a(Yii::t('app', 'Signup'), ['user/signup']) ?>
		<?= Html::a(Yii::t('app', 'Login'), ['user/login']) ?>
    </div>
	<?php ActiveForm::end(); ?>
</div>

views/user/signup.php
<?php
/**
 * Last modified: 18.07.22 10:39:28
 * Hash: fe0340a49f56def8126ae1d065b1c9abbabe3381
 * @var $this yii\web\View
 * @var $model app\models\User
 * @var $form yii\widgets\ActiveForm
 */

use app\models\User;
use himiklab\yii2\recaptcha\ReCaptcha;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

?>

<div class="user signup">
    <div class="logo">
        <img src="/images/logo-black.png" alt="AI Logistics">
    </div>
    <h1><?= Yii::t('app', 'Create an account') ?></h1>

    <p class="description"><?= Yii::t('app', '') ?></p>

    <?php $form = ActiveForm::begin(); ?>
    <div class="fields">
        <?= $form->field($model, 'nick')
            ->textInput([
                'maxlength' => User::NICK_LENGTH,
                'placeholder' => Yii::t('app', 'Enter Your Login')
            ])
            ->label(false) ?>

        <?= $form->field($model, 'email')
            ->textInput([
                'maxlength' => User::EMAIL_LENGTH,
                'placeholder' => Yii::t('app', 'Enter Your Email')
            ])
            ->label(false) ?>

        <?= $form->field($model, 'password')
            ->passwordInput([
                'maxlength' => User::PASSWORD_LENGTH,
                'placeholder' => Yii::t('app', 'Enter Your Password')
            ])
            ->label(false) ?>

        <?= $form->field($model, 'sponsor')
            ->textInput([
                'maxlength' => User::NICK_LENGTH,
                'placeholder' => Yii::t('app', 'Enter Your Sponsor Login')
            ])
            ->label(false) ?>

        <?= $form->field($model, 'ip')->hiddenInput()->label(false) ?>

        <p class="sponsor">
            <?= Yii::t('app', '(Your Sponsor)') ?>
        </p>
    </div>

    <?php if (Yii::$app->settings->get('auth-recaptcha', 0) > 0) {
        echo $form->field($model, 'captcha')->widget(ReCaptcha::class, [
                'size' => ReCaptcha::SIZE_NORMAL
        ])->label(false);
    } ?>

    <div class="control">
        <?= Html::submitButton(Yii::t('app', 'Signup')) ?>
        <?= Html::a(Yii::t('app', 'Login'), ['user/login']) ?>
        <?= Html::a(Yii::t('app', 'Forgot password?'), ['user/request']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>